const state={scope:'committed',market:'all',tech:'all',risk:'all',scenario:'base',data:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt0=new Intl.NumberFormat('en-US',{maximumFractionDigits:0}),fmt1=new Intl.NumberFormat('en-US',{maximumFractionDigits:1});
const riskWeight={low:0,unknown:.45,medium:.65,high:1};
function sum(rows,fn){return rows.reduce((s,r)=>s+(fn(r)||0),0)}
function groupSum(rows,keyFn,valueFn){const m=new Map();for(const r of rows){const k=keyFn(r);m.set(k,(m.get(k)||0)+(valueFn(r)||0))}return [...m.entries()].sort((a,b)=>b[1]-a[1])}
function riskFlagged(a){const v=Object.values(a.risk);return v.includes('high')||v.filter(x=>x==='medium').length>=2}
function anyHigh(a){return Object.values(a.risk).includes('high')}
function riskScore(a){return Math.max(...Object.values(a.risk).map(v=>({low:0,unknown:1,medium:2,high:3}[v]??1)))}
function expectedMWh(a){return a.capacity_mw_ac!=null&&a.generation_cf!=null?a.capacity_mw_ac*8760*a.generation_cf:null}
function normalizedAssets(rows){return rows.filter(a=>a.count_in_normalized_capacity&&a.capacity_mw_ac!=null)}
function displayAssets(){return state.data.assets.filter(a=>{const scopeOK=state.scope==='pipeline'?true:a.count_in_contracted_view;const marketOK=state.market==='all'||a.market===state.market;const techOK=state.tech==='all'||a.technology===state.tech;const riskOK=state.risk==='all'||(state.risk==='flagged'&&riskFlagged(a))||(state.risk==='high'&&anyHigh(a));return scopeOK&&marketOK&&techOK&&riskOK})}
function scopeAssets(){return state.data.assets.filter(a=>state.scope==='pipeline'?true:a.count_in_contracted_view)}
function pct(v){return `${Math.round(v*100)}%`} function mw(v){return `${fmt0.format(v)} MW`} function gw(v){return `${fmt1.format(v/1000)} GW`} function twh(v){return `${fmt1.format(v/1e6)} TWh`}
function solarScenario(a,s){const map=state.data.assumptions.solar_firm_scenarios_by_market;return (map[a.market]||map.default)[s]}
function firmFactor(a,s){if(a.technology==='Solar')return solarScenario(a,s);const f=state.data.assumptions.firm_scenarios[a.technology];return f?f[s]:0}
function firmMW(a,s=state.scenario){return a.capacity_mw_ac!=null&&a.count_in_normalized_capacity?a.capacity_mw_ac*firmFactor(a,s):0}
function dataConfidence(a){let score=0;if(a.capacity_mw_ac!=null&&a.capacity_basis)score+=25;else if(a.capacity_mw_dc!=null&&a.capacity_basis)score+=12;if(a.cod_year!=null||/Operating|Commissioning/i.test(a.status))score+=20;if(a.market&&!/^TBD/i.test(a.market)&&!a.market.includes('/'))score+=15;else if(a.market&&!/^TBD/i.test(a.market))score+=8;if(a.technology&&!/undisclosed/i.test(a.technology))score+=10;else score+=4;if(a.source_url&&a.source_label)score+=15;const known=Object.values(a.risk).filter(v=>v!=='unknown').length;score+=known*5;return Math.min(score,100)}
function weightedAverage(rows,fn){const n=normalizedAssets(rows);const den=sum(n,a=>a.capacity_mw_ac);return den?sum(n,a=>a.capacity_mw_ac*fn(a))/den:0}
function hhi(rows,key){const n=normalizedAssets(rows),total=sum(n,a=>a.capacity_mw_ac);if(!total)return 1;return groupSum(n,a=>a[key],a=>a.capacity_mw_ac).reduce((s,[,v])=>s+(v/total)**2,0)}
function diversificationScore(rows,key){const groups=groupSum(normalizedAssets(rows),a=>a[key],a=>a.capacity_mw_ac).length;if(groups<=1)return 0;const x=hhi(rows,key);const min=1/groups;return Math.max(0,Math.min(100,(1-x)/(1-min)*100))}
function deliveryScore(rows){const n=normalizedAssets(rows),den=sum(n,a=>a.capacity_mw_ac);if(!den)return 0;const penalty=sum(n,a=>a.capacity_mw_ac*(Object.values(a.risk).reduce((s,v)=>s+riskWeight[v],0)/3))/den;return Math.max(0,100*(1-penalty))}
function firmReadinessScore(rows){const n=normalizedAssets(rows),cap=sum(n,a=>a.capacity_mw_ac),base=sum(n,a=>firmMW(a,'base'));return cap?Math.min(100,base/cap*100):0}
function health(rows){const c={delivery:deliveryScore(rows),firm_readiness:firmReadinessScore(rows),market_diversification:diversificationScore(rows,'market'),counterparty_diversification:diversificationScore(rows,'counterparty'),data_confidence:weightedAverage(rows,dataConfidence)};const w=state.data.assumptions.health_score_weights;const score=Object.keys(w).reduce((s,k)=>s+c[k]*w[k],0);return{score,c}}
function populateFilters(){const markets=[...new Set(state.data.assets.map(a=>a.market))].sort(),techs=[...new Set(state.data.assets.map(a=>a.technology))].sort();$('#marketFilter').innerHTML='<option value="all">All markets</option>'+markets.map(x=>`<option>${x}</option>`).join('');$('#techFilter').innerHTML='<option value="all">All technologies</option>'+techs.map(x=>`<option>${x}</option>`).join('')}
function grade(x){return x>=80?'Strong':x>=65?'Moderate':x>=50?'Exposed':'High attention'}
function renderHealth(){const rows=scopeAssets(),h=health(rows),n=Math.round(h.score);$('#healthCard').innerHTML=`<div class="health-score" style="--score:${n}"><div class="health-score-inner"><div class="health-number">${n}</div><div class="health-label">/ 100</div></div></div><div><div class="health-title">Portfolio health · ${grade(n)}</div><div class="health-note">Explainable screening score for the selected committed/pipeline scope. It prioritizes investigation; it does not certify adequacy.</div><div class="health-components">${[['Delivery',h.c.delivery],['Firmness',h.c.firm_readiness],['Markets',h.c.market_diversification],['Counterparty',h.c.counterparty_diversification],['Data',h.c.data_confidence]].map(([k,v])=>`<div class="health-component"><span>${k}</span><strong>${Math.round(v)}</strong></div>`).join('')}</div></div>`}
function attentionScore(a,total){const cap=a.capacity_mw_ac||0,impact=total?cap/total:0;const vals=Object.values(a.risk);const riskLoad=vals.reduce((s,v)=>s+riskWeight[v],0)/3;const highs=vals.filter(v=>v==='high').length,mediums=vals.filter(v=>v==='medium').length;const near=a.cod_year?Math.max(0,(2032-a.cod_year)/6):0;const gap=(100-dataConfidence(a))/100;return riskLoad*45+highs*10+mediums*4+impact*35+near*10+gap*15}
function attentionReasons(a,total){const r=[];for(const [k,v] of Object.entries(a.risk))if(v==='high')r.push(`${k} risk high`);if(a.cod_year==null)r.push('COD unresolved');if(dataConfidence(a)<80)r.push(`data confidence ${dataConfidence(a)}/100`);if(a.capacity_mw_ac&&total&&a.capacity_mw_ac/total>.12)r.push(`${Math.round(a.capacity_mw_ac/total*100)}% of scoped MWac`);if(!r.length&&Object.values(a.risk).filter(x=>x==='medium').length>=2)r.push('multiple medium delivery risks');return r.slice(0,2).join(' · ')||'Largest remaining exposure in current scope'}
function renderAttention(){const rows=displayAssets(),n=normalizedAssets(rows),total=sum(n,a=>a.capacity_mw_ac);const ranked=rows.filter(a=>riskFlagged(a)||dataConfidence(a)<80||a.cod_year==null).sort((a,b)=>attentionScore(b,total)-attentionScore(a,total)).slice(0,3);$('#attentionList').innerHTML=ranked.map((a,i)=>`<div class="attention-item"><div class="attention-rank">Priority ${i+1}</div><div class="attention-name">${a.asset_name}</div><div class="attention-reason">${attentionReasons(a,total)}</div><div class="attention-impact">${a.capacity_mw_ac!=null?mw(a.capacity_mw_ac):fmt0.format(a.capacity_mw_dc||0)+' MWdc'} · ${a.status}</div></div>`).join('')||'<div class="empty">No elevated items in this scope.</div>'}
function renderKPIs(rows){const n=normalizedAssets(rows),cap=sum(n,a=>a.capacity_mw_ac),low=sum(n,a=>firmMW(a,'low')),base=sum(n,a=>firmMW(a,'base')),high=sum(n,a=>firmMW(a,'high')),gen=sum(n,a=>expectedMWh(a)),riskMW=sum(n.filter(riskFlagged),a=>a.capacity_mw_ac),confidence=weightedAverage(rows,dataConfidence),gaps=rows.filter(a=>dataConfidence(a)<80).length;$('#kpis').innerHTML=`<div class="kpi"><div class="kpi-label">Normalized capacity</div><div class="kpi-value accent">${gw(cap)}</div><div class="kpi-note">Defensible MWac in current filtered view</div></div><div class="kpi"><div class="kpi-label">Firm scenario</div><div class="kpi-value">${gw(state.scenario==='low'?low:state.scenario==='high'?high:base)}</div><div class="kpi-note">Low ${gw(low)} · Base ${gw(base)} · High ${gw(high)}</div></div><div class="kpi"><div class="kpi-label">Expected generation</div><div class="kpi-value">${twh(gen)}</div><div class="kpi-note">AC-rated rows with usable capacity factor</div></div><div class="kpi"><div class="kpi-label">COD-risk exposure</div><div class="kpi-value ${riskMW?'bad':''}">${gw(riskMW)}</div><div class="kpi-note">MWac with a high cause or 2+ medium causes</div></div><div class="kpi"><div class="kpi-label">Weighted data confidence</div><div class="kpi-value">${Math.round(confidence)}/100</div><div class="kpi-note">Unit, COD, market, tech, source and risk completeness</div></div><div class="kpi"><div class="kpi-label">Low-confidence rows</div><div class="kpi-value">${gaps}</div><div class="kpi-note">Rows below 80/100 confidence</div></div>`}
function renderBars(target,entries,{limit=7,format=mw}={}){const root=$(target),d=entries.slice(0,limit);if(!d.length){root.innerHTML='<div class="empty">No data in this filter.</div>';return}const max=Math.max(...d.map(x=>x[1]),1);root.innerHTML=d.map(([label,value])=>`<div class="bar-row"><div class="bar-label" title="${label}">${label}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(value/max*100,1)}%"></div></div><div class="bar-value">${format(value)}</div></div>`).join('')}
function renderFirmScenario(rows){const n=normalizedAssets(rows),vals=['low','base','high'].map(s=>[s,sum(n,a=>firmMW(a,s))]),max=Math.max(...vals.map(x=>x[1]),1);$('#firmScenario').innerHTML=`<div class="scenario-stack">${vals.map(([s,v])=>`<div class="scenario-row ${s===state.scenario?'active':''}"><div class="scenario-label">${s[0].toUpperCase()+s.slice(1)}</div><div class="scenario-track"><div class="scenario-fill" style="width:${v/max*100}%"></div></div><div class="scenario-value">${gw(v)}</div></div>`).join('')}</div><div class="scenario-note">Sensitivity range only. Solar varies by market; storage remains constrained because public duration/accreditation is incomplete.</div>`}
function riskExposureEntries(rows){const n=normalizedAssets(rows),keys=['regulatory','interconnection','construction'];return keys.map(k=>[k[0].toUpperCase()+k.slice(1),sum(n.filter(a=>a.risk[k]==='high'||a.risk[k]==='medium'),a=>a.capacity_mw_ac)])}
function campusFirmAt(c,year){return sum(state.data.assets.filter(a=>a.campus_link===c.id&&a.count_in_contracted_view&&a.count_in_normalized_capacity&&a.capacity_mw_ac!=null&&a.cod_year!=null&&a.cod_year<=year),a=>firmMW(a,state.scenario))}
function renderCampusTimeline(){const years=[2026,2028,2030,2032,2034,2035],cs=state.data.campuses;$('#campusTimeline').innerHTML=`<div class="campus-table"><div class="campus-line header"><span>Year</span>${cs.map(c=>`<span>${c.name}</span>`).join('')}</div>${years.map(y=>`<div class="campus-line"><span class="campus-year">${y}</span>${cs.map(c=>{const v=campusFirmAt(c,y),p=Math.min(v/c.load_proxy_mw,1);return`<div class="campus-meter" title="${mw(v)} vs ${mw(c.load_proxy_mw)} ultimate compute-scale proxy"><div class="campus-meter-fill" style="width:${p*100}%"></div><span>${fmt0.format(v)} MW · ${pct(v/c.load_proxy_mw)}</span></div>`}).join('')}</div>`).join('')}</div><div class="campus-foot">Cumulative committed supply by public COD year versus ultimate announced compute scale. This is not a forecast demand ramp.</div>`}
function renderCharts(rows){const n=normalizedAssets(rows);renderBars('#marketChart',groupSum(n,a=>a.market,a=>a.capacity_mw_ac),{limit:7});renderFirmScenario(rows);renderBars('#riskExposure',riskExposureEntries(rows),{limit:3});const cp=groupSum(n,a=>a.counterparty,a=>a.capacity_mw_ac),total=sum(n,a=>a.capacity_mw_ac);renderBars('#counterpartyChart',cp.map(([k,v])=>[k,v/total]),{limit:7,format:v=>pct(v)});const mk=groupSum(n,a=>a.market,a=>a.capacity_mw_ac);renderBars('#marketShareChart',mk.map(([k,v])=>[k,v/total]),{limit:7,format:v=>pct(v)});$('#counterpartyHHI').textContent=`HHI ${fmt0.format(hhi(rows,'counterparty')*10000)}`;$('#marketHHI').textContent=`HHI ${fmt0.format(hhi(rows,'market')*10000)}`;renderCampusTimeline()}
function renderQuality(rows){const items=[['Average confidence',`${Math.round(weightedAverage(rows,dataConfidence))}/100`],['MWdc-only rows',rows.filter(a=>a.capacity_mw_ac==null&&a.capacity_mw_dc!=null).length],['COD unresolved',rows.filter(a=>a.cod_year==null).length],['Queue risk unknown',rows.filter(a=>a.risk.interconnection==='unknown').length],['Aggregate multi-market rows',rows.filter(a=>a.market.includes('/')).length]];$('#qualityList').innerHTML=items.map(([l,v])=>`<div class="quality-item"><span>${l}</span><strong>${v}</strong></div>`).join('')}
function capacityCell(a){if(a.capacity_mw_ac!=null&&a.capacity_mw_dc!=null)return`<div class="capacity-main">${fmt0.format(a.capacity_mw_ac)} MWac</div><div class="capacity-sub">${fmt0.format(a.capacity_mw_dc)} MWdc disclosed</div>`;if(a.capacity_mw_ac!=null)return`<div class="capacity-main">${fmt0.format(a.capacity_mw_ac)} MW</div><div class="capacity-sub">${a.capacity_basis}</div>`;return`<div class="capacity-main">${fmt0.format(a.capacity_mw_dc)} MWdc</div><div class="capacity-sub">AC unresolved · excluded</div>`}
function riskTags(a){const labels={regulatory:'Reg',interconnection:'IX',construction:'Build'};return`<div class="risk-tags">${Object.entries(a.risk).map(([k,v])=>`<span class="risk-tag risk-${v}">${labels[k]} · ${v}</span>`).join('')}</div>`}
function confidenceCell(a){const c=dataConfidence(a);return`<div class="confidence ${c<80?'low':''}"><div class="confidence-bar"><div class="confidence-fill" style="width:${c}%"></div></div><strong>${c}</strong></div>`}
function firmRangeCell(a){if(a.capacity_mw_ac==null||!a.count_in_normalized_capacity)return'<span class="asset-sub">Not normalized</span>';return`<div class="capacity-main">${fmt0.format(firmMW(a,'low'))}–${fmt0.format(firmMW(a,'high'))} MW</div><div class="capacity-sub">Base ${fmt0.format(firmMW(a,'base'))} MW</div>`}
function renderTable(rows){const sorted=[...rows].sort((a,b)=>riskScore(b)-riskScore(a)||(100-dataConfidence(b))-(100-dataConfidence(a))||(b.capacity_mw_ac||0)-(a.capacity_mw_ac||0));$('#tableCount').textContent=`${sorted.length} rows · ${normalizedAssets(sorted).length} normalized into MWac`;$('#assetRows').innerHTML=sorted.map(a=>`<tr><td><div class="asset-name">${a.asset_name}</div><div class="asset-sub">${a.counterparty} · ${a.structure}</div></td><td><div class="asset-name">${a.market}</div><div class="asset-sub">${a.state}</div></td><td>${a.technology}</td><td>${capacityCell(a)}</td><td><div class="asset-name">${a.cod_label}</div><div class="asset-sub">${a.status}</div></td><td>${firmRangeCell(a)}</td><td>${confidenceCell(a)}</td><td>${riskTags(a)}</td><td><button class="detail-button" data-asset="${a.id}">Details</button></td></tr>`).join('')||'<tr><td colspan="9" class="empty">No rows match these filters.</td></tr>';$$('[data-asset]').forEach(b=>b.addEventListener('click',()=>openAsset(b.dataset.asset)))}
function openAsset(id){const a=state.data.assets.find(x=>x.id===id);if(!a)return;$('#assetDialogTitle').textContent=a.asset_name;const conf=dataConfidence(a),exp=expectedMWh(a);$('#assetDialogBody').innerHTML=`<div class="detail-grid"><div class="detail-box"><span>Counterparty</span><strong>${a.counterparty}</strong></div><div class="detail-box"><span>Market</span><strong>${a.market}</strong></div><div class="detail-box"><span>Capacity basis</span><strong>${a.capacity_basis}</strong></div><div class="detail-box"><span>COD</span><strong>${a.cod_label}</strong></div><div class="detail-box"><span>Firm range</span><strong>${a.capacity_mw_ac!=null?`${fmt0.format(firmMW(a,'low'))} / ${fmt0.format(firmMW(a,'base'))} / ${fmt0.format(firmMW(a,'high'))} MW`:'Not normalized'}</strong></div><div class="detail-box"><span>Data confidence</span><strong>${conf}/100</strong></div></div><h3>Risk lineage</h3>${riskTags(a)}<p><strong>Status:</strong> ${a.status}</p><p><strong>Expected generation:</strong> ${exp==null?'Not calculated':twh(exp)+' / year'}</p><h3>Public evidence</h3><p>${a.source_label}</p><p><a class="source-link" href="${a.source_url}" target="_blank" rel="noreferrer">Open primary public source ↗</a></p><h3>Normalization note</h3><p>${a.notes||'No additional note.'}</p>`;$('#assetDialog').showModal()}
function renderHourly(){const rows=normalizedAssets(scopeAssets());const hourly=[];for(let h=0;h<24;h++){let v=0;for(const a of rows){let shape=1;if(a.technology==='Solar'){const x=(h-6)/12*Math.PI;shape=h>=6&&h<=18?Math.max(0,Math.sin(x)):0}else if(a.technology==='Battery')shape=0;v+=(a.capacity_mw_ac||0)*shape}hourly.push(v)}const max=Math.max(...hourly,1);$('#hourlyShape').innerHTML=hourly.map((v,h)=>`<div class="hour-bar" data-hour="${h}:00" style="height:${Math.max(v/max*100,2)}%" title="Hour ${h}: illustrative portfolio output index ${fmt0.format(v)}"></div>`).join('')}
function renderMethod(){const w=state.data.assumptions.health_score_weights;$('#methodContent').innerHTML=`<h3>Portfolio Health Score</h3><p>Weighted composite: delivery ${pct(w.delivery)}, firm readiness ${pct(w.firm_readiness)}, market diversification ${pct(w.market_diversification)}, counterparty diversification ${pct(w.counterparty_diversification)}, and data confidence ${pct(w.data_confidence)}. It is a transparent screening construct, not a Meta KPI.</p><h3>Firmness scenarios</h3><p>Low/base/high ranges stress-test technology contribution. Solar varies by market. Storage is deliberately conservative because duration and accreditation are incomplete. No value is presented as ISO-accredited capacity.</p><h3>COD risk</h3><p>Delivery exposure is capacity-weighted across regulatory, interconnection and construction risk. High risks receive the largest penalty; unknowns remain a penalty rather than being treated as safe.</p><h3>Data confidence</h3><p>Each asset is scored for capacity-unit resolution, COD visibility, market specificity, technology specificity, source traceability and risk completeness.</p><h3>Concentration</h3><p>HHI is calculated from MWac shares. It is a capacity concentration measure, not financial, credit or mark-to-market exposure.</p>`}
function render(){const rows=displayAssets();renderHealth();renderAttention();renderKPIs(rows);renderCharts(rows);renderQuality(rows);renderTable(rows);renderHourly();renderMethod();window.PortfolioApp={state,filterAssets:displayAssets,health,firmMW,dataConfidence};document.dispatchEvent(new Event("portfolio:updated"))}
function bindNav(){const links=$$('.nav-item[href^="#"]');const sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);links.forEach(a=>a.addEventListener('click',()=>{links.forEach(x=>x.classList.remove('active'));a.classList.add('active')}));if('IntersectionObserver'in window){const obs=new IntersectionObserver(entries=>{const hit=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!hit)return;links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${hit.target.id}`))},{rootMargin:'-20% 0px -65% 0px',threshold:[0,.1,.25,.5]});sections.forEach(s=>obs.observe(s))}}
function bindUI(){$$('.seg').forEach(btn=>btn.addEventListener('click',()=>{$$('.seg').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.scope=btn.dataset.scope;render()}));$('#marketFilter').addEventListener('change',e=>{state.market=e.target.value;render()});$('#techFilter').addEventListener('change',e=>{state.tech=e.target.value;render()});$('#riskFilter').addEventListener('change',e=>{state.risk=e.target.value;render()});$('#scenarioFilter').addEventListener('change',e=>{state.scenario=e.target.value;render()});$('#resetBtn').addEventListener('click',()=>{state.market=state.tech=state.risk='all';state.scenario='base';$('#marketFilter').value=$('#techFilter').value=$('#riskFilter').value='all';$('#scenarioFilter').value='base';render()});$('#methodBtn').addEventListener('click',()=>$('#methodDialog').showModal());$('#whyBtn').addEventListener('click',()=>$('#whyDialog').showModal());$$('[data-close]').forEach(btn=>btn.addEventListener('click',()=>$('#'+btn.dataset.close).close()));$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}))}
fetch('/data/portfolio.json').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(data=>{state.data=data;populateFilters();bindUI();bindNav();render()}).catch(err=>{document.body.innerHTML=`<main class="shell"><div class="notice"><strong>Data load failed.</strong> Serve the project over HTTP rather than opening index.html directly.<br><br>${err.message}</div></main>`});
