(() => {
  'use strict';
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let installed=false,brief='';
  function render(){const app=window.PortfolioApp;if(!app)return;
    if(!installed){installed=true;const section=document.createElement('section');section.id='procurement';section.className='ops-section';section.innerHTML='<div class="section-heading"><div><h2>Procurement decision readiness</h2><p>Evidence required from each specialist team before progressing a portfolio decision.</p></div><span class="section-meta">Cross-team handoffs</span></div><div id="gateGrid" class="gate-grid"></div><article class="card leadership-brief"><div class="card-head"><div><span class="card-kicker">Automated reporting · rule-based</span><h3>Leadership brief</h3></div><button class="button secondary" id="downloadExecutive">Download brief</button></div><div id="executiveBrief"></div><p class="monitor-note">Generated from the applied dataset and explicit screening rules. Human review required. No LLM, live-feed monitoring or automatic procurement execution.</p></article>';$('#portfolio').after(section);
      const nav=document.createElement('a');nav.className='nav-item';nav.href='#procurement';nav.textContent='Procurement readiness';$('.side-nav').append(nav);
      $('#downloadExecutive').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([brief],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download='portfolio-leadership-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
    const rows=app.filterAssets(),n=rows.length,normal=rows.filter(a=>a.count_in_normalized_capacity&&Number.isFinite(a.capacity_mw_ac)),total=normal.reduce((s,a)=>s+a.capacity_mw_ac,0),flagged=normal.filter(a=>Object.values(a.risk).includes('high')||Object.values(a.risk).filter(x=>x==='medium').length>=2),riskMW=flagged.reduce((s,a)=>s+a.capacity_mw_ac,0);
    const gates=[
      {name:'Source & definitions',owner:'Data / Analytics',count:rows.filter(a=>!a.source_url||!a.source_label||!a.capacity_basis).length,need:'Traceable source, capacity basis and shared field definitions.',handoff:'Analytics → all Energy teams'},
      {name:'Delivery milestones',owner:'Asset Management',count:rows.filter(a=>a.cod_year==null||Object.values(a.risk).includes('high')).length,need:'Confirmed COD, critical path and mitigation evidence.',handoff:'Asset Management → Origination'},
      {name:'Market allocation',owner:'Wholesale',count:rows.filter(a=>!a.market||/TBD|\//i.test(a.market)).length,need:'Resolved market, delivery point and basis exposure.',handoff:'Wholesale → Origination'},
      {name:'Commercial evaluation',owner:'Origination / Finance',count:null,need:'Contract prices, terms, credit support and comparable alternatives are absent.',handoff:'Origination → decision forum'},
      {name:'Load & deliverability',owner:'Infrastructure / Wholesale',count:null,need:'Electrical demand, timing, transmission rights and accredited capacity are absent.',handoff:'Infrastructure → portfolio planning'},
      {name:'Evidence freshness',owner:'Data / Source owners',count:null,need:'Asset-level verification timestamps and refresh SLAs are absent.',handoff:'Source owners → Analytics'}
    ];
    $('#gateGrid').innerHTML=gates.map(g=>`<article class="card gate"><span class="gate-state ${g.count===0&&n?'documented':''}">${!n?'No assets':g.count==null?'Not available':g.count?g.count+' rows need review':'Fields present'}</span><h3>${g.name}</h3><p>${esc(g.need)}</p><div class="gate-owner">${g.owner}</div><small>${g.handoff}</small></article>`).join('');
    const s=app.state,top=[...flagged].sort((a,b)=>b.capacity_mw_ac-a.capacity_mw_ac)[0],fmt=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(v);
    const sections=[['Situation',n?`${n} asset rows in ${s.scope==='pipeline'?'committed + pipeline':'committed'} scope; ${s.market==='all'?'all markets':s.market}; ${s.tech==='all'?'all technologies':s.tech}; ${s.risk} risk filter. ${fmt(total)} MWac normalized; ${s.scenario} firmness screening.`:'No assets in the applied view. Broaden the filters before reviewing readiness.'],['Exposure',`${fmt(riskMW)} MWac is delivery-risk flagged${total?' ('+Math.round(riskMW/total*100)+'% of normalized capacity)':''}. ${rows.length-normal.length} rows remain outside normalized totals. Exclusions and data gaps are not zero exposure.`],['Priority handoff',top?`${top.asset_name} is the largest flagged normalized exposure at ${fmt(top.capacity_mw_ac)} MWac. Asset Management and the relevant regulatory/grid functions should reconcile its critical path before Origination relies on the schedule.`:'No flagged normalized asset in this view. Review unresolved data and commercial inputs before drawing a procurement conclusion.'],['Decision requested','Agree the evidence owners and review dates for unresolved delivery, market and commercial inputs. Keep procurement approval pending until specialist review establishes economics, load fit and deliverability.'],['Next forum','Suggested weekly integration review: close data exceptions and dependencies. Monthly portfolio review: compare supply timing, exposure and procurement alternatives. Escalate missed decision dates through the action register.']];
    $('#executiveBrief').innerHTML=sections.map(([label,text])=>`<div><h4>${label}</h4><p>${esc(text)}</p></div>`).join('');
    brief=['ENERGY PORTFOLIO LEADERSHIP BRIEF',new Date().toISOString(),...sections.map(([l,t])=>'\n'+l+'\n'+t),'\nREADINESS CHECKS',...gates.map(g=>`${g.name}: ${!n?'No assets':g.count==null?'Not available':g.count+' rows need review'}. Owner: ${g.owner}. ${g.need}`),'\nSOURCE LINEAGE',...rows.map(a=>`${a.asset_name}: ${a.source_url}`),'\nPublic-disclosure screening. Fields present is not independently verified. Rule-based draft; human review required.'].join('\n');
  }
  document.addEventListener('portfolio:updated',render);render();
})();
